# Generated by Django 5.0.1 on 2024-01-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_category_id_alter_game_category_id_and_more'),
        ('mainpage', '0002_category_created_at_category_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainpage.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainpage.category'),
        ),
    ]
