# Generated by Django 5.0.1 on 2024-01-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_category_id_alter_item_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
