# Generated by Django 5.0.1 on 2024-01-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_src',
            field=models.CharField(max_length=200),
        ),
    ]
