# Generated by Django 5.0.1 on 2024-01-07 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='api.user'),
        ),
    ]
