# Generated by Django 5.0.1 on 2024-01-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_player_id_alter_game_owner_id'),
        ('mainpage', '0003_rename_category_name_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.category'),
        ),
    ]
