# Generated by Django 5.0.1 on 2024-01-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_src',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
