# Generated by Django 5.0.1 on 2024-01-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_game_url_alter_item_img_src_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_src',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
