# Generated by Django 5.0.1 on 2024-01-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_category_created_at_category_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
