# Generated by Django 5.0.1 on 2024-01-07 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_src',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
    ]
