# Generated by Django 5.0.1 on 2024-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_category_img_src_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_src',
            field=models.TextField(),
        ),
    ]
