# Generated by Django 5.0.1 on 2024-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_category_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_src',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='mainpage/static/mainpage/'),

        ),
    ]
